$('#Bates').evoCalendar({   sidebarToggler: false, eventListToggler: false,  theme:'Orange Coral', calendarEvents: [
 { id:'2414' ,name: "Unavail Click for bot", date: "2022/11/07", description:"all", type: "tourclosed" },
 { id:'2415' ,name: "Unavail Click for bot", date: "2022/11/08", description:"all", type: "tourclosed" },
 { id:'2416' ,name: "Avail (Click to book)", date: "2022/11/09", description:"all", type: "touropen" },
 { id:'2417' ,name: "Avail (Click to book)", date: "2022/11/10", description:"all", type: "touropen" },
 { id:'2418' ,name: "Unavail Click for bot", date: "2022/11/11", description:"all", type: "tourclosed" },
 { id:'2419' ,name: "Avail (Click to book)", date: "2022/11/12", description:"all", type: "touropen" },
 { id:'2420' ,name: "Avail (Click to book)", date: "2022/11/14", description:"all", type: "touropen" },
 { id:'2421' ,name: "Avail (Click to book)", date: "2022/11/15", description:"all", type: "touropen" },
 { id:'2422' ,name: "Avail (Click to book)", date: "2022/11/16", description:"all", type: "touropen" },
 { id:'2423' ,name: "Avail (Click to book)", date: "2022/11/17", description:"all", type: "touropen" },
 { id:'2424' ,name: "Avail (Click to book)", date: "2022/11/18", description:"all", type: "touropen" },
 { id:'2425' ,name: "Avail (Click to book)", date: "2022/11/28", description:"all", type: "touropen" },
 { id:'2426' ,name: "Avail (Click to book)", date: "2022/11/29", description:"all", type: "touropen" },
 { id:'2427' ,name: "Avail (Click to book)", date: "2022/11/30", description:"all", type: "touropen" },
 { id:'2428' ,name: "Avail (Click to book)", date: "2022/12/01", description:"all", type: "touropen" },
 { id:'2429' ,name: "Avail (Click to book)", date: "2022/12/02", description:"all", type: "touropen" },
 { id:'2430' ,name: "Avail (Click to book)", date: "2022/12/05", description:"all", type: "touropen" },
 { id:'2431' ,name: "Avail (Click to book)", date: "2022/12/06", description:"all", type: "touropen" },
 { id:'2432' ,name: "Avail (Click to book)", date: "2022/12/07", description:"all", type: "touropen" },
 { id:'2433' ,name: "Avail (Click to book)", date: "2022/12/08", description:"all", type: "touropen" },
 { id:'2434' ,name: "Avail (Click to book)", date: "2022/12/09", description:"all", type: "touropen" },

], });$('#Bates').on('selectEvent', function(event,activeEvent) {if(activeEvent.type=='touropen') {	window.open('https://apply.bates.edu/portal/campus-visit_vNew'); } else { window.location.href='/tourrequest.jsp?cname=Bates&date='+activeEvent.date+'&times='+activeEvent.description;     }});
