$('#Baylor').evoCalendar({   sidebarToggler: false, eventListToggler: false,  theme:'Orange Coral', calendarEvents: [
 { id:'291' ,name: "Unavail Click for bot", date: "2022/11/07", description:"all", type: "tourclosed" },
 { id:'292' ,name: "Unavail Click for bot", date: "2022/11/08", description:"all", type: "tourclosed" },
 { id:'293' ,name: "Unavail Click for bot", date: "2022/11/09", description:"all", type: "tourclosed" },
 { id:'294' ,name: "Unavail Click for bot", date: "2022/11/10", description:"all", type: "tourclosed" },
 { id:'295' ,name: "Unavail Click for bot", date: "2022/11/11", description:"all", type: "tourclosed" },
 { id:'296' ,name: "Unavail Click for bot", date: "2022/11/14", description:"all", type: "tourclosed" },
 { id:'297' ,name: "Avail (Click to book)", date: "2022/11/15", description:"all", type: "touropen" },
 { id:'298' ,name: "Avail (Click to book)", date: "2022/11/16", description:"all", type: "touropen" },
 { id:'299' ,name: "Avail (Click to book)", date: "2022/11/17", description:"all", type: "touropen" },
 { id:'300' ,name: "Unavail Click for bot", date: "2022/11/18", description:"all", type: "tourclosed" },
 { id:'301' ,name: "Unavail Click for bot", date: "2022/11/21", description:"all", type: "tourclosed" },
 { id:'302' ,name: "Unavail Click for bot", date: "2022/11/28", description:"all", type: "tourclosed" },
 { id:'303' ,name: "Avail (Click to book)", date: "2022/11/29", description:"all", type: "touropen" },
 { id:'304' ,name: "Avail (Click to book)", date: "2022/11/30", description:"all", type: "touropen" },
 { id:'305' ,name: "Unavail Click for bot", date: "2022/12/01", description:"all", type: "tourclosed" },
 { id:'306' ,name: "Unavail Click for bot", date: "2022/12/02", description:"all", type: "tourclosed" },
 { id:'307' ,name: "Avail (Click to book)", date: "2022/12/05", description:"all", type: "touropen" },
 { id:'308' ,name: "Avail (Click to book)", date: "2022/12/06", description:"all", type: "touropen" },
 { id:'309' ,name: "Avail (Click to book)", date: "2022/12/07", description:"all", type: "touropen" },
 { id:'310' ,name: "Avail (Click to book)", date: "2022/12/08", description:"all", type: "touropen" },
 { id:'311' ,name: "Unavail Click for bot", date: "2022/12/09", description:"all", type: "tourclosed" },

], });$('#Baylor').on('selectEvent', function(event,activeEvent) {if(activeEvent.type=='touropen') {	window.open('https://apply.baylor.edu/portal/visit_experience'); } else { window.location.href='/tourrequest.jsp?cname=Baylor&date='+activeEvent.date+'&times='+activeEvent.description;     }});
