$('#DePauw').evoCalendar({   sidebarToggler: false, eventListToggler: false,  theme:'Orange Coral', calendarEvents: [
 { id:'494' ,name: "Unavail Click for bot", date: "2022/11/07", description:"all,all,any", type: "tourclosed" },
 { id:'495' ,name: "Unavail Click for bot", date: "2022/11/08", description:"all,all,any", type: "tourclosed" },
 { id:'496' ,name: "Avail (Click to book)", date: "2022/11/09", description:"all,all", type: "touropen" },
 { id:'497' ,name: "Avail (Click to book)", date: "2022/11/10", description:"all,all", type: "touropen" },
 { id:'498' ,name: "Avail (Click to book)", date: "2022/11/11", description:"all", type: "touropen" },
 { id:'499' ,name: "Unavail Click for bot", date: "2022/11/11", description:"all", type: "tourclosed" },
 { id:'500' ,name: "Avail (Click to book)", date: "2022/11/14", description:"all,all", type: "touropen" },
 { id:'501' ,name: "Avail (Click to book)", date: "2022/11/15", description:"all,all", type: "touropen" },
 { id:'502' ,name: "Avail (Click to book)", date: "2022/11/16", description:"all,all", type: "touropen" },
 { id:'503' ,name: "Avail (Click to book)", date: "2022/11/17", description:"all,all", type: "touropen" },
 { id:'504' ,name: "Unavail Click for bot", date: "2022/11/18", description:"8:00 AM", type: "tourclosed" },
 { id:'505' ,name: "Avail (Click to book)", date: "2022/11/19", description:"all", type: "touropen" },
 { id:'506' ,name: "Avail (Click to book)", date: "2022/11/21", description:"all,all", type: "touropen" },
 { id:'507' ,name: "Avail (Click to book)", date: "2022/11/22", description:"all,all", type: "touropen" },
 { id:'508' ,name: "Avail (Click to book)", date: "2022/11/23", description:"all,all", type: "touropen" },
 { id:'509' ,name: "Avail (Click to book)", date: "2022/11/28", description:"all,all", type: "touropen" },
 { id:'510' ,name: "Avail (Click to book)", date: "2022/11/29", description:"all,all", type: "touropen" },
 { id:'511' ,name: "Avail (Click to book)", date: "2022/11/30", description:"all,all", type: "touropen" },
 { id:'512' ,name: "Avail (Click to book)", date: "2022/12/01", description:"all,all", type: "touropen" },
 { id:'513' ,name: "Avail (Click to book)", date: "2022/12/02", description:"all,all", type: "touropen" },
 { id:'514' ,name: "Avail (Click to book)", date: "2022/12/05", description:"all,all", type: "touropen" },
 { id:'515' ,name: "Avail (Click to book)", date: "2022/12/06", description:"all,all", type: "touropen" },
 { id:'516' ,name: "Avail (Click to book)", date: "2022/12/07", description:"all,all", type: "touropen" },
 { id:'517' ,name: "Avail (Click to book)", date: "2022/12/08", description:"all,all", type: "touropen" },
 { id:'518' ,name: "Avail (Click to book)", date: "2022/12/09", description:"all,all", type: "touropen" },
 { id:'519' ,name: "Avail (Click to book)", date: "2022/12/12", description:"all,all", type: "touropen" },
 { id:'520' ,name: "Avail (Click to book)", date: "2022/12/13", description:"all,all", type: "touropen" },
 { id:'521' ,name: "Avail (Click to book)", date: "2022/12/14", description:"all,all", type: "touropen" },
 { id:'522' ,name: "Avail (Click to book)", date: "2022/12/15", description:"all,all", type: "touropen" },
 { id:'523' ,name: "Avail (Click to book)", date: "2022/12/16", description:"all,all", type: "touropen" },
 { id:'524' ,name: "Avail (Click to book)", date: "2022/12/19", description:"all,all", type: "touropen" },
 { id:'525' ,name: "Avail (Click to book)", date: "2022/12/20", description:"all,all", type: "touropen" },
 { id:'526' ,name: "Avail (Click to book)", date: "2022/12/21", description:"all,all", type: "touropen" },

], });$('#DePauw').on('selectEvent', function(event,activeEvent) {if(activeEvent.type=='touropen') {	window.open('https://apply.depauw.edu/portal/CampusVisit'); } else { window.location.href='/tourrequest.jsp?cname=DePauw&date='+activeEvent.date+'&times='+activeEvent.description;     }});
