$('#Holy_Cross').evoCalendar({   sidebarToggler: false, eventListToggler: false,  theme:'Orange Coral', calendarEvents: [
 { id:'3275' ,name: "Avail (Click to book)", date: "2022/11/07", description:"all", type: "touropen" },
 { id:'3276' ,name: "Avail (Click to book)", date: "2022/11/08", description:"all,7:00 PM", type: "touropen" },
 { id:'3277' ,name: "Avail (Click to book)", date: "2022/11/09", description:"all", type: "touropen" },
 { id:'3278' ,name: "Avail (Click to book)", date: "2022/11/10", description:"all", type: "touropen" },
 { id:'3279' ,name: "Avail (Click to book)", date: "2022/11/11", description:"all", type: "touropen" },
 { id:'3280' ,name: "Avail (Click to book)", date: "2022/11/12", description:"all", type: "touropen" },
 { id:'3281' ,name: "Avail (Click to book)", date: "2022/11/14", description:"all", type: "touropen" },
 { id:'3282' ,name: "Avail (Click to book)", date: "2022/11/15", description:"all", type: "touropen" },
 { id:'3283' ,name: "Avail (Click to book)", date: "2022/11/16", description:"all", type: "touropen" },
 { id:'3284' ,name: "Avail (Click to book)", date: "2022/11/17", description:"all", type: "touropen" },
 { id:'3285' ,name: "Avail (Click to book)", date: "2022/11/18", description:"all", type: "touropen" },
 { id:'3286' ,name: "Avail (Click to book)", date: "2022/11/21", description:"all", type: "touropen" },
 { id:'3287' ,name: "Avail (Click to book)", date: "2022/11/22", description:"all", type: "touropen" },
 { id:'3288' ,name: "Avail (Click to book)", date: "2022/11/28", description:"all", type: "touropen" },
 { id:'3289' ,name: "Avail (Click to book)", date: "2022/11/29", description:"all", type: "touropen" },
 { id:'3290' ,name: "Avail (Click to book)", date: "2022/11/30", description:"all", type: "touropen" },
 { id:'3291' ,name: "Avail (Click to book)", date: "2022/12/01", description:"all", type: "touropen" },
 { id:'3292' ,name: "Avail (Click to book)", date: "2022/12/02", description:"all", type: "touropen" },
 { id:'3293' ,name: "Avail (Click to book)", date: "2022/12/05", description:"all", type: "touropen" },
 { id:'3294' ,name: "Avail (Click to book)", date: "2022/12/06", description:"all", type: "touropen" },
 { id:'3295' ,name: "Avail (Click to book)", date: "2022/12/07", description:"all", type: "touropen" },
 { id:'3296' ,name: "Avail (Click to book)", date: "2022/12/08", description:"all", type: "touropen" },
 { id:'3297' ,name: "Avail (Click to book)", date: "2022/12/09", description:"all", type: "touropen" },

], });$('#Holy_Cross').on('selectEvent', function(event,activeEvent) {if(activeEvent.type=='touropen') {	window.open('https://admissions.holycross.edu/portal/campusvisit'); } else { window.location.href='/tourrequest.jsp?cname=Holy_Cross&date='+activeEvent.date+'&times='+activeEvent.description;     }});
