$('#Northwestern').evoCalendar({   sidebarToggler: false, eventListToggler: false,  theme:'Orange Coral', calendarEvents: [
 { id:'872' ,name: "Avail (Click to book)", date: "2022/11/07", description:"all", type: "touropen" },
 { id:'873' ,name: "Avail (Click to book)", date: "2022/11/08", description:"all", type: "touropen" },
 { id:'874' ,name: "Avail (Click to book)", date: "2022/11/09", description:"all", type: "touropen" },
 { id:'875' ,name: "Avail (Click to book)", date: "2022/11/10", description:"all", type: "touropen" },
 { id:'876' ,name: "Avail (Click to book)", date: "2022/11/11", description:"all", type: "touropen" },
 { id:'877' ,name: "Avail (Click to book)", date: "2022/11/12", description:"all", type: "touropen" },
 { id:'878' ,name: "Avail (Click to book)", date: "2022/11/14", description:"all", type: "touropen" },
 { id:'879' ,name: "Avail (Click to book)", date: "2022/11/15", description:"all", type: "touropen" },
 { id:'880' ,name: "Avail (Click to book)", date: "2022/11/16", description:"all", type: "touropen" },
 { id:'881' ,name: "Avail (Click to book)", date: "2022/11/17", description:"all", type: "touropen" },
 { id:'882' ,name: "Avail (Click to book)", date: "2022/11/18", description:"all", type: "touropen" },
 { id:'883' ,name: "Avail (Click to book)", date: "2022/11/19", description:"all", type: "touropen" },
 { id:'884' ,name: "Avail (Click to book)", date: "2022/11/21", description:"all", type: "touropen" },
 { id:'885' ,name: "Avail (Click to book)", date: "2022/11/22", description:"all", type: "touropen" },
 { id:'886' ,name: "Avail (Click to book)", date: "2022/11/28", description:"all", type: "touropen" },
 { id:'887' ,name: "Avail (Click to book)", date: "2022/11/29", description:"all", type: "touropen" },
 { id:'888' ,name: "Avail (Click to book)", date: "2022/11/30", description:"all", type: "touropen" },
 { id:'889' ,name: "Avail (Click to book)", date: "2022/12/01", description:"all", type: "touropen" },
 { id:'890' ,name: "Avail (Click to book)", date: "2022/12/02", description:"all", type: "touropen" },
 { id:'891' ,name: "Avail (Click to book)", date: "2022/12/05", description:"all", type: "touropen" },
 { id:'892' ,name: "Avail (Click to book)", date: "2022/12/06", description:"all", type: "touropen" },
 { id:'893' ,name: "Avail (Click to book)", date: "2022/12/07", description:"all", type: "touropen" },
 { id:'894' ,name: "Avail (Click to book)", date: "2022/12/08", description:"all", type: "touropen" },
 { id:'895' ,name: "Avail (Click to book)", date: "2022/12/09", description:"all", type: "touropen" },
 { id:'896' ,name: "Avail (Click to book)", date: "2022/12/12", description:"all", type: "touropen" },
 { id:'897' ,name: "Avail (Click to book)", date: "2022/12/13", description:"all", type: "touropen" },
 { id:'898' ,name: "Avail (Click to book)", date: "2022/12/14", description:"all", type: "touropen" },
 { id:'899' ,name: "Avail (Click to book)", date: "2022/12/15", description:"all", type: "touropen" },
 { id:'900' ,name: "Avail (Click to book)", date: "2022/12/16", description:"all", type: "touropen" },

], });$('#Northwestern').on('selectEvent', function(event,activeEvent) {if(activeEvent.type=='touropen') {	window.open('https://ugadmission.northwestern.edu/portal/visit'); } else { window.location.href='/tourrequest.jsp?cname=Northwestern&date='+activeEvent.date+'&times='+activeEvent.description;     }});
