$('#Scripps').evoCalendar({   sidebarToggler: false, eventListToggler: false,  theme:'Orange Coral', calendarEvents: [
 { id:'3298' ,name: "Avail (Click to book)", date: "2022/11/07", description:"all", type: "touropen" },
 { id:'3299' ,name: "Avail (Click to book)", date: "2022/11/08", description:"all", type: "touropen" },
 { id:'3300' ,name: "Avail (Click to book)", date: "2022/11/09", description:"all", type: "touropen" },
 { id:'3301' ,name: "Avail (Click to book)", date: "2022/11/10", description:"all", type: "touropen" },
 { id:'3302' ,name: "Avail (Click to book)", date: "2022/11/11", description:"all", type: "touropen" },
 { id:'3303' ,name: "Avail (Click to book)", date: "2022/11/12", description:"all", type: "touropen" },
 { id:'3304' ,name: "Avail (Click to book)", date: "2022/11/14", description:"all", type: "touropen" },
 { id:'3305' ,name: "Avail (Click to book)", date: "2022/11/15", description:"all", type: "touropen" },
 { id:'3306' ,name: "Avail (Click to book)", date: "2022/11/16", description:"all", type: "touropen" },
 { id:'3307' ,name: "Avail (Click to book)", date: "2022/11/17", description:"all", type: "touropen" },
 { id:'3308' ,name: "Avail (Click to book)", date: "2022/11/18", description:"all", type: "touropen" },
 { id:'3309' ,name: "Avail (Click to book)", date: "2022/11/19", description:"all", type: "touropen" },
 { id:'3310' ,name: "Avail (Click to book)", date: "2022/11/28", description:"all", type: "touropen" },
 { id:'3311' ,name: "Avail (Click to book)", date: "2022/11/29", description:"all", type: "touropen" },
 { id:'3312' ,name: "Avail (Click to book)", date: "2022/11/30", description:"all", type: "touropen" },
 { id:'3313' ,name: "Avail (Click to book)", date: "2022/12/01", description:"all", type: "touropen" },
 { id:'3314' ,name: "Avail (Click to book)", date: "2022/12/02", description:"all", type: "touropen" },
 { id:'3315' ,name: "Avail (Click to book)", date: "2022/12/03", description:"all", type: "touropen" },
 { id:'3316' ,name: "Avail (Click to book)", date: "2022/12/05", description:"all", type: "touropen" },
 { id:'3317' ,name: "Avail (Click to book)", date: "2022/12/06", description:"all", type: "touropen" },
 { id:'3318' ,name: "Avail (Click to book)", date: "2022/12/07", description:"all", type: "touropen" },

], });$('#Scripps').on('selectEvent', function(event,activeEvent) {if(activeEvent.type=='touropen') {	window.open('https://apply.scrippscollege.edu/portal/campus-visit'); } else { window.location.href='/tourrequest.jsp?cname=Scripps&date='+activeEvent.date+'&times='+activeEvent.description;     }});
